### ISSUE TITLE
--watch continuously compiles assets 

### ISSUE THREAD

**Issue by ghost** [skaryys/encore-require-assets-helper#1]
Hi,

with the new symfony 4 and the configuration here, the command `yarn run encore dev --watch` starts to compile the assets again and again.

this is my config for this asset helper:

`
var Encore = require('@symfony/webpack-encore');
var requireAssetsHelper = require("encore-require-assets-helper");

requireAssetsHelper(
    "./assets/images/**/*.{jpg,jpeg,png,gif,svg,ico}",
    "./assets/js/assets.js",
    "",
    "../../"
);

Encore
    .setOutputPath('public/build/')
    .setPublicPath('/build')
    .cleanupOutputBeforeBuild()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())

    .addEntry('js/landingpage', './assets/js/landingpage.js')
    .addStyleEntry('css/landingpage', './assets/scss/landingpage.scss')
    
    .enableSassLoader()
    .autoProvidejQuery()
;

module.exports = Encore.getWebpackConfig();
`

Somehow sounds logical, cause webpack watches the asset folder for changes and with the config above it writes a new assets.js file into the asset folder ? but i tried to change the path, that this plugin writes the new assets.js file into /public/, but still having this problem.

anyone experiencing the same problem or am i doing something wrong ?

**Comment by skaryys** [comment]
Hi,

ok, your configuration seems OK, i think there will be some problem cause of new versions of symfony/webpack-encore. It seems that the compile is being done after every file is writed into the "assets.js" file of encore-require-assets-helper. So if you have more images in your project, it might be really problem.

Maybe the solution will be if the file will be writed only in one step? I will try something in some free time.

**EDIT**
Ok, i tried generate the "assets.js" file at once, but it did not help. It seems nowadays, the Encore watch even the images required in javascript files. I hope I will figure out some solution.

**EDIT 2:**
The only solution I figured out so far is runnig the requireAssetsHelper function outside the webpack.config.js.
So that is the new rule of this package now. 
Probably it is possible to figure out something better, but my knowledge is far away from that. But you can still work with package as you were so far, but with bigger amount of images, its almost impossible to run encore with watch.

**Comment by ghost** [comment]
thanks for your time!
